name: Hello World

on:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      uses: action/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash